export const FETCH_BIRTHDAYS = "FETCH_BIRTHDAYS";
export const GET_BIRTHDAY = "GET_BIRTHDAY";
export const CREATE_BIRTHDAY = "CREATE_BIRTHDAY";
export const UPDATE_BIRTHDAY = "UPDATE_BIRTHDAY";
export const DELETE_BIRTHDAY = "DELETE_BIRTHDAY";
export const CREATE_POST = "CREATE_POST";
export const UPDATE_POST = "UPDATE_POST";
export const DELETE_POST = "DELETE_POST";

// home birthdays
export const FETCH_HOMEBIRTHDAYS = "FETCH_HOMEBIRTHDAYS";
export const GET_HOMEBIRTHDAY = "GET_HOMEBIRTHDAY";
export const CREATE_HOMEPOST = "CREATE_HOMEPOST";
export const DELETE_HOMEPOST = "DELETE_HOMEPOST";
export const UPDATE_HOMEPOST = "UDATE_HOMEPOST";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
